[k3s_server]
control_plane ansible_host=13.63.160.44 private_ip=10.0.1.89

[k3s_agents]
worker1 ansible_host=10.0.1.143 private_ip=10.0.1.143
worker2 ansible_host=10.0.1.231 private_ip=10.0.1.231

[k3s_agents:vars]
ansible_ssh_common_args='-o StrictHostKeyChecking=no -o ProxyJump=ubuntu@13.63.160.44'

[all:vars]
ansible_user=ubuntu
ansible_ssh_private_key_file=~/.ssh/id_ed25519
