---
- name: Apply base hardening and networking configurations
  hosts: all
  become: true
  roles:
    - hardening

- name: Install and configure k3s control plane
  hosts: k3s_server
  become: true
  roles:
    - k3s-server

- name: Install and join k3s workers
  hosts: k3s_agents
  become: true
  roles:
    - k3s-agent
